/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IFlatColorIcons:like': typeof import('~icons/flat-color-icons/like')['default']
    'IFluentEmoji:loveLetter': typeof import('~icons/fluent-emoji/love-letter')['default']
    'INotoV1:loveHotel': typeof import('~icons/noto-v1/love-hotel')['default']
    ISimpleLineIconsFrame: typeof import('~icons/simple-line-icons/frame')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Video: typeof import('./src/components/video/index.vue')['default']
  }
}
